# Generated by Django 2.1 on 2018-08-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='last_thread_hid',
        ),
        migrations.AddField(
            model_name='board',
            name='last_post_hid',
            field=models.IntegerField(null=True),
        ),
    ]
