# Generated by Django 2.1 on 2018-08-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_auto_20180810_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='last_post_hid',
        ),
    ]
