# Generated by Django 2.1 on 2018-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0004_board_custom_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replies',
        ),
        migrations.AddField(
            model_name='post',
            name='refs',
            field=models.ManyToManyField(db_index=True, editable=False, to='imageboard.Post'),
        ),
    ]
