# Generated by Django 2.1 on 2018-12-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0005_auto_20181010_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='max_threads_num',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='board',
            name='posts_per_thread_per_page',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='board',
            name='threads_per_page',
            field=models.IntegerField(default=10),
        ),
    ]
