# Generated by Django 2.1.5 on 2019-01-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0008_post_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='board',
            name='custom_style',
            field=models.TextField(blank=True, help_text="Custom CSS that would be applied only on this board's pages", verbose_name='Custom style'),
        ),
        migrations.AlterField(
            model_name='board',
            name='default_max_posts_num',
            field=models.IntegerField(help_text="Maximum number of posts for new threads by default. Can be overridden in thread's properties.", verbose_name='Default maximum posts number'),
        ),
        migrations.AlterField(
            model_name='board',
            name='default_username',
            field=models.CharField(help_text="Default username will be saved, if post's author field was empty.", max_length=32, verbose_name='Default username'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, help_text='Short board description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='board',
            name='hid',
            field=models.CharField(db_index=True, max_length=8, verbose_name='HID'),
        ),
        migrations.AlterField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Boards is removed from boards list and can't be accessed by direct URL.", verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='board',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Is this board hidden from boards list. Can still be accessed by direct URL.', verbose_name='Is hidden'),
        ),
        migrations.AlterField(
            model_name='board',
            name='is_locked',
            field=models.BooleanField(default=False, help_text="New posts and threads can't be created on locked board.", verbose_name='Is locked'),
        ),
        migrations.AlterField(
            model_name='board',
            name='last_post_hid',
            field=models.IntegerField(null=True, verbose_name='Last post HID'),
        ),
        migrations.AlterField(
            model_name='board',
            name='max_threads_num',
            field=models.IntegerField(default=100, help_text='Maximum number of threads on this boards. When reaching this level older threads will be deleted.', verbose_name='Maximum threads number'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='board',
            name='posts_per_thread_per_page',
            field=models.IntegerField(default=5, help_text="Number of thread's posts visible on board's pages, not counting OP post.", verbose_name='Posts per thread per page'),
        ),
        migrations.AlterField(
            model_name='board',
            name='rules',
            field=models.TextField(blank=True, help_text='Board rules will be displayed next to posting form.', verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='board',
            name='threads_per_page',
            field=models.IntegerField(default=10, help_text="Number of threads on board's page", verbose_name='Threads per page'),
        ),
        migrations.AlterField(
            model_name='board',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='board',
            name='url',
            field=models.CharField(max_length=16, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='checksum',
            field=models.CharField(blank=True, editable=False, max_length=32, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(editable=False, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_spoiler',
            field=models.BooleanField(default=False, verbose_name='Is spoiler'),
        ),
        migrations.AlterField(
            model_name='image',
            name='mimetype',
            field=models.CharField(editable=False, max_length=16, verbose_name='MIME type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_name',
            field=models.CharField(editable=False, max_length=128, verbose_name='Original name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imageboard.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.IntegerField(editable=False, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb_height',
            field=models.IntegerField(editable=False, verbose_name='Thumb height'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb_width',
            field=models.IntegerField(editable=False, verbose_name='Thumb width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(editable=False, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=32, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(blank=True, max_length=32, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hid',
            field=models.IntegerField(db_index=True, editable=False, verbose_name='HID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ip_address',
            field=models.CharField(db_index=True, editable=False, max_length=16, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_op',
            field=models.BooleanField(editable=False, verbose_name='Is OP'),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=16, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='post',
            name='refs',
            field=models.ManyToManyField(db_index=True, editable=False, to='imageboard.Post', verbose_name='Refs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='session_id',
            field=models.CharField(db_index=True, editable=False, max_length=32, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='imageboard.Thread', verbose_name='Thread'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_was_banned',
            field=models.BooleanField(default=False, verbose_name='User was banned'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_was_warned',
            field=models.BooleanField(default=False, verbose_name='User was warned'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='imageboard.Board', verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='hid',
            field=models.IntegerField(db_index=True, editable=False, verbose_name='HID'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is locked'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='is_sticky',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is sticky'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='max_posts_num',
            field=models.IntegerField(verbose_name='Maximum posts number'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imageboard.Post', verbose_name='OP'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at'),
        ),
    ]
