# Generated by Django 2.1.5 on 2019-02-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0009_auto_20190129_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['hid'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
    ]
