# Generated by Django 2.1.5 on 2019-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0010_auto_20190204_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='url',
        ),
        migrations.AlterField(
            model_name='board',
            name='default_max_posts_num',
            field=models.IntegerField(default=128, help_text="Maximum number of posts for new threads by default. Can be overridden in thread's properties.", verbose_name='Default maximum posts number'),
        ),
    ]
