# Generated by Django 2.1.5 on 2019-02-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0011_auto_20190208_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, help_text='Short board description', max_length=256, verbose_name='Description'),
        ),
    ]
