# Generated by Django 2.1 on 2018-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=32)),
                ('solution', models.CharField(max_length=8)),
                ('image', models.TextField()),
            ],
        ),
    ]
