# Generated by Django 2.1.5 on 2019-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='solution',
            field=models.CharField(max_length=32),
        ),
    ]
