# Generated by Django 2.1.5 on 2019-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0002_auto_20190126_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captcha',
            options={'verbose_name': 'Captcha', 'verbose_name_plural': 'Captchas'},
        ),
        migrations.AlterField(
            model_name='captcha',
            name='image',
            field=models.TextField(verbose_name='Encoded image'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='public_id',
            field=models.CharField(max_length=32, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='solution',
            field=models.CharField(max_length=32, verbose_name='Solution'),
        ),
    ]
