# Generated by Django 2.1.5 on 2019-01-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banreason',
            name='code',
        ),
        migrations.AlterField(
            model_name='banreason',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
