# Generated by Django 2.1.5 on 2019-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_auto_20190127_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='type',
            field=models.CharField(choices=[('ip', 'IP address'), ('network', 'Network'), ('session', 'Session')], max_length=8),
        ),
    ]
