# Generated by Django 2.1.5 on 2019-01-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_auto_20190127_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={'verbose_name': 'Ban', 'verbose_name_plural': 'Bans'},
        ),
        migrations.AlterModelOptions(
            name='banreason',
            options={'verbose_name': 'Ban reason', 'verbose_name_plural': 'Ban reasons'},
        ),
        migrations.AlterModelOptions(
            name='imagefilter',
            options={'verbose_name': 'Image filter', 'verbose_name_plural': 'Image filters'},
        ),
        migrations.AlterModelOptions(
            name='wordfilter',
            options={'verbose_name': 'Word filter', 'verbose_name_plural': 'Word filters'},
        ),
        migrations.AlterField(
            model_name='ban',
            name='active_until',
            field=models.DateTimeField(verbose_name='Active until'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.BanReason', verbose_name='Ban reason'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='type',
            field=models.CharField(choices=[('ip', 'IP address'), ('network', 'Network'), ('session', 'Session')], max_length=8, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='value',
            field=models.CharField(max_length=32, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='banreason',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='checksum',
            field=models.CharField(max_length=32, verbose_name='Checksum'),
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='imagefilter',
            name='size',
            field=models.IntegerField(verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='wordfilter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='wordfilter',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='wordfilter',
            name='expression',
            field=models.CharField(max_length=256, verbose_name='Regular expression'),
        ),
    ]
